MODE: "debug"
Port: 9090

GOOGLE_SECRET_KEY: "{{GOOGLE_SECRET_KEY}}"
GOOLE_CLIENT_ID: "{{GOOLE_CLIENT_ID}}"

# 30days
JWT_TOKEN_LIFE: 30
JWT_SECRET: "vWe3gYDEThzLK2ROAJSZPm7kmsDi88c20noscs8AqyuEc4t9UNLqXYS16OmYy0O"