MODE: "debug"
Port: 9090

DB_HOST: "0.0.0.0"
DB_PORT: "3306"
DB_USER: "root"
DB_PASS: "1234"
DB_DATABASE: "pomo"

REDIS_HOST: "0.0.0.0"
REDIS_PORT: "6379"
REDIS_PASS: ""

DB_MAX_CONN: 800
DB_IDLE_CONN: 20
DB_MAX_LIFE_TIME: 10

GOOGLE_SECRET_KEY: "{{GOOGLE_SECRET_KEY}}"
GOOLE_CLIENT_ID: "{{GOOLE_CLIENT_ID}}"

# 30days
JWT_TOKEN_LIFE: 2592000 
JWT_SECRET: "vWe3gYDEThzLK2ROAJSZPm7kmsDi88c20noscs8AqyuEc4t9UNLqXYS16OmYy0O"