version: '2'

services:
  db: 
    image: mysql:5.6
    ports:
        - "3306:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=1234
    volumes:
        - ./mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest 
    ports:
        - "9000:80"
    links:
        - db
  redis:
    image: redis:latest
    ports:
        - "6379:6379"

  phpredisadmin:
    image: erikdubbelboer/phpredisadmin:latest
    ports:
        - "9300:80"
    environment:
        - ADMIN_USER=admin
        - ADMIN_PASS=admin
        - REDIS_1_HOST=redis
        - REDIS_1_PORT=6379
    links:
        - redis

  frontend:
    image: node:14.9.0
    volumes:
        - ./frontend:/code
    command: tail -F anything
    ports:
        - "8080:8080"

  backend:
    image: golang:1.15.1
    volumes:
        - .:/go/src/code
    command: tail -F anything
    ports:
        - "9090:9090"